// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdVl-cTICSwYKrjn-0hI9ctcWDNIdKJQw',
    appId: '1:297855924061:web:669ac284ee374e7c5b9ba6',
    messagingSenderId: '297855924061',
    projectId: 'billie-music-app',
    authDomain: 'billie-music-app.firebaseapp.com',
    storageBucket: 'billie-music-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdVl-cTICSwYKrjn-0hI9ctcWDNIdKJQw',
    appId: '1:297855924061:android:ac3b909a3b5bb7c95b9ba6',
    messagingSenderId: '297855924061',
    projectId: 'billie-music-app',
    authDomain: 'billie-music-app.firebaseapp.com',
    storageBucket: 'billie-music-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdVl-cTICSwYKrjn-0hI9ctcWDNIdKJQw',
    appId: '1:297855924061:ios:ac3b909a3b5bb7c95b9ba6',
    messagingSenderId: '297855924061',
    projectId: 'billie-music-app',
    authDomain: 'billie-music-app.firebaseapp.com',
    storageBucket: 'billie-music-app.appspot.com',
    iosBundleId: 'com.gokadzev.musify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdVl-cTICSwYKrjn-0hI9ctcWDNIdKJQw',
    appId: '1:297855924061:macos:ac3b909a3b5bb7c95b9ba6',
    messagingSenderId: '297855924061',
    projectId: 'billie-music-app',
    authDomain: 'billie-music-app.firebaseapp.com',
    storageBucket: 'billie-music-app.appspot.com',
    iosBundleId: 'com.gokadzev.musify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdVl-cTICSwYKrjn-0hI9ctcWDNIdKJQw',
    appId: '1:297855924061:windows:ac3b909a3b5bb7c95b9ba6',
    messagingSenderId: '297855924061',
    projectId: 'billie-music-app',
    authDomain: 'billie-music-app.firebaseapp.com',
    storageBucket: 'billie-music-app.appspot.com',
  );
}